env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
rules: {
  semi: ["error", "never"],
  no-unused-vars: 1,
  no-case-declarations: 0,
  prettier/prettier: "warn",
}